language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
jdk:
  - openjdk7
env:
  - 'JRUBY_OPTS="-X-C --server -J-XX:+TieredCompilation"'
before_install:
  - 'rm -rf $rvm_path/gems/*/{bin,gems}/rubygems-bundler-* $rvm_path/gems/*/bin/ruby_*_wrapper'
  - hash -r
  - gem install rake
install: gem install tf -v '>=0.4.1'
before_script:
  - unset BUNDLE_GEMFILE
script: tf --text test/dtf/*
notifications:
  irc:
    channels:
      - "irc.freenode.org#rubygems-bundler"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: ruby-head
