# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81a045e24dbde5605935f9cbcc441082af469275c53a84e2aa9a412789c877fcc8b57f3ecdfbc96910d0ab355260ea339582d8b75c9edac39d79c6f44fdf0287
  postmark_api_token: <%= ENV['POSTMARK_API_TOKEN'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>

test:
  secret_key_base: 8182a5da85e3cd1070cff08ababb6a624d45d09c763a5640e40f5842e8d79f6a62dee193a2ddf6c4c593b04d5c2200dd6627e9c76b8cf0d989f335c8c6b36ebd
  postmark_api_token: <%= ENV['POSTMARK_API_TOKEN'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmark_api_token: <%= ENV['POSTMARK_API_TOKEN'] %>
  google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
